server:
  port: 8080

spring:
  application:
    name: kingboy-springboot-data
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mybatis?characterEncoding=utf8&useSSL=false
mybatis:
  configuration:
    map-underscore-to-camel-case: true